[package]
edition = "2024.alpha"
name = "counter"

[dependencies]
Sui = {git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet"}

[addresses]
counter = "0x0"
