[package]
edition = "2024.alpha"
name = "SharedCapWithPointer"
published-at = "0x0e4233631538681b8cfac312cf381aa1adc7554ca7b3e5055c33dc23ed552b13"
version = "0.1.1"

[dependencies]
Sui = {git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet"}

[addresses]
# shared_cap = "0x0"
shared_cap = "0x0e4233631538681b8cfac312cf381aa1adc7554ca7b3e5055c33dc23ed552b13"
